apiVersion: v1
kind: Secret
metadata:
  name: mongosync
type: Opaque
stringData:
  config.yml: |
    cluster0: "mongodb://admin:password@cluster.namespace.svc"
    cluster1: "mongodb://admin:password@new-cluster.namespace.svc"
    verbosity: "WARN"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongosync
  name: mongosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosync
  template:
    metadata:
      labels:
        app: mongosync
    spec:
      volumes:
        - name: mongosync
          secret:
            secretName: mongosync
      containers:
      - image: balthazar0/mongosync
        name: mongosync
        args: ["--config", "/etc/mongosync/config.yml"]
        ports:
        - containerPort: 27182
          name: api
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/progress
        #     port: api
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/progress
        #     port: api
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        volumeMounts:
          - name: mongosync
            readOnly: true
            mountPath: "/etc/mongosync"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongosync
  name: mongosync
spec:
  selector:
    app: mongosync
  type: ClusterIP
  ports:
  - name: api
    port: 27182
    protocol: TCP
    targetPort: api
