apiVersion: v1
kind: Secret
metadata:
  name: mongosync
type: Opaque
stringData:
  # Refer to https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/configuration/#configuration for more options.
  mongosync.yml: |
    cluster0: "mongodb://mongosync-user:<strong-password>@mongos.mongodb.svc.cluster.local:27017"
    cluster1: "mongodb://mongosync-user:<strong-password>@192.168.32.64:27017"
    logPath: "/var/log/mongosync"
    verbosity: "WARN"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongosync
  name: mongosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosync
  template:
    metadata:
      labels:
        app: mongosync
    spec:
      volumes:
        - name: mongosync
          secret:
            secretName: mongosync
      containers:
      - image: balthazar0/mongosync
        name: mongosync
        command: ["--config", "/etc/mongosync.conf"]
        ports:
        - containerPort: 27182
          name: api
        livenessProbe:
          httpGet:
            path: /api/v1/progress
            port: api
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/progress
            port: api
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: MONGOSYNC_CLUSTER_0
          valueFrom:
            secretKeyRef:
              name: mongosync
              key: MONGOSYNC_CLUSTER_0
        - name: MONGOSYNC_CLUSTER_1
          valueFrom:
            secretKeyRef:
              name: mongosync
              key: MONGOSYNC_CLUSTER_1
        volumeMounts:
          - name: mongosync
            readOnly: true
            mountPath: "/etc/"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongosync
  name: mongosync
spec:
  selector:
    app: mongosync
  type: ClusterIP
  ports:
  - name: api
    port: 27182
    protocol: TCP
    targetPort: api
